// GENERATED by scripts/gen-tested-versions.mjs from test/fixtures/claude-code/. Do not edit; run `npm run gen:versions`.
// Claude Code versions we hold captured, redacted fixtures for.
export const TESTED_CLAUDE_VERSIONS: readonly string[] = ["2.1.277","2.1.278","2.1.280","2.1.282","2.1.284"];
// Requested models and max_tokens values seen in those fixtures' requests (src/wire/drift.ts).
export const FIXTURE_REQUESTED_MODELS: readonly string[] = ["claude-haiku-4-5-20251001","claude-opus-5","claude-opus-5-5","claude-sonnet-5"];
export const FIXTURE_MAX_TOKENS: readonly number[] = [1,64,32000,64000,128000];
